name = "gfl-trunk"
type = "javascript"
compatibility_date = "2024-12-10"
main = "functions/_middleware.js"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.js", "src/**/*.css"]

[env.production]
name = "gfl-trunk-production"

[build.upload]
format = "modules"
dir = "build"
