// Brand data configuration for the 12 Gardens
// Each brand corresponds to a slide in the Gardens slideshow



// Generate metrics for each brand
const generateMetrics = () => [
  { label: "Innovation", value: Math.floor(Math.random() * 50) + 50, description: "Tech score" },
  { label: "Design", value: Math.floor(Math.random() * 50) + 50, description: "Aesthetics" },
  { label: "Utility", value: Math.floor(Math.random() * 50) + 50, description: "Usability" },
  { label: "Price", value: Math.floor(Math.random() * 50) + 50, description: "Market value" },
  { label: "Sustain", value: Math.floor(Math.random() * 50) + 50, description: "Eco impact" },
  { label: "Performance", value: Math.floor(Math.random() * 50) + 50, description: "Raw output" },
];

// All 12 slots are template placeholders (expandable when real brands are added)
export const BRANDS = [
  // Placeholder brands 01-04 — template slots
  { id: '01', slug: 'template-01', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '\u2014\u2014', origin: '\u2014\u2014', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
  { id: '02', slug: 'template-02', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '\u2014\u2014', origin: '\u2014\u2014', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
  { id: '03', slug: 'template-03', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '\u2014\u2014', origin: '\u2014\u2014', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
  { id: '04', slug: 'template-04', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '\u2014\u2014', origin: '\u2014\u2014', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
  // Placeholder brands 05-12 — template slots
  {
    id: '05',
    slug: 'template',
    name: 'BINNENKORT',
    tagline: 'Jouw brandpagina op het platform',
    description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.',
    foundedYear: '——',
    origin: '——',
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E",
    accentColor: '#00ff9d',
    metrics: generateMetrics(),
    gallery: [
      { id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' },
    ],
    featuredProducts: [
      { id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] },
      { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] },
    ],
    events: [
      { id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' },
      { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' },
    ],
    reviews: [
      { id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' },
      { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' },
    ],
    tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'],
    email: 'contact@gardenforlife.nl',
    socialLinks: [
      { platform: 'web', url: '#' },
      { platform: 'insta', url: '#' },
      { platform: 'linkedin', url: '#' },
    ]
  },
  // Placeholder brands 06-12 — all use the same template as unit 05
  { id: '06', slug: 'template-06', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '——', origin: '——', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
  { id: '07', slug: 'template-07', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '——', origin: '——', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
  { id: '08', slug: 'template-08', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '——', origin: '——', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
  { id: '09', slug: 'template-09', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '——', origin: '——', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
  { id: '10', slug: 'template-10', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '——', origin: '——', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
  { id: '11', slug: 'template-11', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '——', origin: '——', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
  { id: '12', slug: 'template-12', name: 'BINNENKORT', tagline: 'Jouw brandpagina op het platform', description: 'Jouw bedrijfsprofiel wordt hier weergegeven. Als partner van Garden for Life deel je hier jouw verhaal, je aanbod en je visie met de community. Neem contact met ons team op om je brandpagina te activeren en je merk zichtbaar te maken.', foundedYear: '——', origin: '——', logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='50' fill='%23ffffff08' stroke='%23ffffff20' stroke-width='2'/%3E%3Ctext x='50' y='62' text-anchor='middle' fill='%23ffffff25' font-size='42' font-family='monospace'%3E%3F%3C/text%3E%3C/svg%3E", heroImageUrl: '', accentColor: '#00ff9d', metrics: generateMetrics(), gallery: [{ id: '1', type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4', title: 'Introductie' }], featuredProducts: [{ id: 'p1', name: 'Product / Dienst A', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }, { id: 'p2', name: 'Product / Dienst B', price: 'Op aanvraag', specs: ['Beschrijving', 'Nader te bepalen'] }], events: [{ id: 'e1', date: 'Nader te bepalen', title: 'Evenement / Activiteit A', location: 'Locatie volgt' }, { id: 'e2', date: 'Nader te bepalen', title: 'Evenement / Activiteit B', location: 'Locatie volgt' }], reviews: [{ id: 'r1', user: 'Partner_01', rating: 5, comment: 'Reviews worden hier weergegeven zodra de pagina live is.' }, { id: 'r2', user: 'Partner_02', rating: 5, comment: 'Jouw klanten kunnen hier hun ervaringen delen.' }], tags: ['Jouw categorie', 'Jouw niche', 'Garden for Life'], email: 'contact@gardenforlife.nl', socialLinks: [{ platform: 'web', url: '#' }, { platform: 'insta', url: '#' }, { platform: 'linkedin', url: '#' }] },
];
// Get brand by index (0-11)
export const getBrandByIndex = (index) => {
  return BRANDS[index % BRANDS.length];
};

// Get brand by slug
export const getBrandBySlug = (slug) => {
  return BRANDS.find(brand => brand.slug === slug);
};

// Get brand by ID
export const getBrandById = (id) => {
  return BRANDS.find(brand => brand.id === id);
};

export default BRANDS;
