/**
 * eyedentityReport — copy for the Eyedentity "Persoonlijk Profiel" tab.
 *
 * Covers the sample AI report sections, the cognitive-triangle block, the
 * owner-only manage panel and the standalone feedback form messages.
 *
 * NOTE — "Deltawerken" is a proper name and stays untranslated in both languages.
 *
 * The section keys under `sections` mirror the `id` of each entry in
 * HARDCODED_SECTIONS (apps/platform/src/pages/EyedentityPage.jsx). That file keeps
 * the Dutch `title` string as a language-independent routing key for the section
 * grouping + accent colour; the rendered title/body come from here.
 */
export default {
  eyedentityReport: {
    // ── Page shell ──
    shell: {
      protocolLabel: {
        nl: 'Persoonlijk Protocol Interface',
        en: 'Personal Protocol Interface',
      },
    },

    // ── Owner-only manage panel ──
    manage: {
      open: { nl: 'Beheer', en: 'Manage' },
      close: { nl: 'Sluiten', en: 'Close' },
      displayNameLabel: { nl: 'Zichtbare naam', en: 'Display name' },
      save: { nl: 'Opslaan', en: 'Save' },
      saved: { nl: 'Opgeslagen ✓', en: 'Saved ✓' },
      saveFailed: { nl: 'Bijwerken mislukt', en: 'Update failed' },
      profileCodeLabel: { nl: 'Profielcode', en: 'Profile code' },
      copyCode: { nl: 'Kopieer code', en: 'Copy code' },
      // The word the user must type to confirm account deletion. Kept in sync with
      // the placeholder + inline <b> in the confirmation sentence.
      deleteWord: { nl: 'VERWIJDER', en: 'DELETE' },
      deleteIntroBefore: {
        nl: 'Dit verwijdert je account en alle assessments permanent (AVG/GDPR). Typ ',
        en: 'This permanently deletes your account and all assessments (GDPR). Type ',
      },
      deleteIntroAfter: {
        nl: ' om te bevestigen:',
        en: ' to confirm:',
      },
      deleteMismatch: {
        nl: 'Typ precies "VERWIJDER" om te bevestigen',
        en: 'Type exactly "DELETE" to confirm',
      },
      deleteFailed: { nl: 'Verwijderen mislukt', en: 'Deletion failed' },
      deleting: { nl: 'Bezig...', en: 'Working...' },
      delete: { nl: 'Verwijderen', en: 'Delete' },
    },

    // ── Meta-disclaimer above the report ──
    metaDisclaimer: {
      label: { nl: 'Meta-Disclaimer:', en: 'Meta-Disclaimer:' },
      body: {
        nl: 'Dit rapport is gegenereerd door het Garden For Life Deltawerken Model — een zelfreflectie-instrument, geen klinische diagnose. De gebruikte neurobiologische termen zijn metaforen binnen dit specifieke model. Raadpleeg een professional voor medisch of psychologisch advies.',
        en: 'This report was generated by the Garden For Life Deltawerken Model — a self-reflection instrument, not a clinical diagnosis. The neurobiological terms used here are metaphors within this specific model. Consult a professional for medical or psychological advice.',
      },
    },

    // ── Fallback subgroup axis labels (SubgroupCounters demo data) ──
    axes: {
      ruling: { nl: 'Autoriteit & Structuur', en: 'Authority & Structure' },
      relational: { nl: 'Relatie & Verbinding', en: 'Relationship & Connection' },
      seeker: { nl: 'Waarheid & Ontdekking', en: 'Truth & Discovery' },
      chaos: { nl: 'Disruptie & Perspectief', en: 'Disruption & Perspective' },
      abstract: { nl: 'Wijsheid & Creatie', en: 'Wisdom & Creation' },
      agency: { nl: 'Manifestatie & Actie', en: 'Manifestation & Action' },
    },

    // ── Cognitive triangle block ──
    cog: {
      heading: { nl: 'Cognitieve Driehoek', en: 'Cognitive Triangle' },
      // The intro paragraph carries inline <strong>/<em> emphasis, so it is split
      // into the fragments the JSX interleaves.
      introA: {
        nl: 'Gele driehoeken vuren uitsluitend op ',
        en: 'Yellow triangles fire exclusively on ',
      },
      introCulturePicks: { nl: 'Culture picks', en: 'Culture picks' },
      introB: {
        nl: ' — ze representeren aangeleerd cognitief gedrag, niet biologische hardware. Groene en blauwe signalen tonen wie je ',
        en: ' — they represent learned cognitive behaviour, not biological hardware. Green and blue signals show who you ',
      },
      introAre: { nl: 'bent', en: 'are' },
      introC: {
        nl: '; gele signalen tonen hoe je hebt ',
        en: '; yellow signals show how you have ',
      },
      introLearned: { nl: 'leren navigeren', en: 'learned to navigate' },
      introD: { nl: '.', en: '.' },

      driveLabel: { nl: 'Aangeleerde navigatie: ', en: 'Learned navigation: ' },
      highLabel: { nl: 'Hoog geel profiel: ', en: 'High yellow profile: ' },
      growthLabel: { nl: 'Groeirichting: ', en: 'Growth direction: ' },

      modes: {
        idealisme: {
          mode: { nl: 'Idealisme Modus', en: 'Idealism Mode' },
          networks: { nl: 'CEN · Openness · DMN', en: 'CEN · Openness · DMN' },
          tagline: {
            nl: 'Ik navigeer via principes, visie en structuur.',
            en: 'I navigate through principles, vision and structure.',
          },
          what: {
            nl: 'Mijn aangeleerde cognitieve gedrag organiseert zich rondom het bouwen van systemen die kloppen. Niet alleen praktisch — ook moreel. Ruler, Innocent en Sage vormen samen een driehoek die zoekt naar de ideale orde: een wereld die gehoorzaamt aan beginselen waarvan ik geloof dat ze universeel geldig zijn.',
            en: 'My learned cognitive behaviour organises itself around building systems that hold up. Not only practically — morally as well. Ruler, Innocent and Sage together form a triangle that searches for the ideal order: a world that obeys principles I believe to be universally valid.',
          },
          drive: {
            nl: 'Aangeleerde navigatie: Mijn Culture picks tonen dat ik heb leren navigeren via autoriteit en visie (Ruler), reinheid en beginseltrouw (Innocent), en kennis als kompas (Sage). Je bouwt mentale architectuur — frameworks, overtuigingen, systemen — als aangeleerde strategie om de chaos te beheersen.',
            en: 'Learned navigation: My Culture picks show that I have learned to navigate through authority and vision (Ruler), purity and loyalty to principle (Innocent), and knowledge as a compass (Sage). You build mental architecture — frameworks, convictions, systems — as a learned strategy for keeping chaos under control.',
          },
          high: {
            nl: 'Hoog geel profiel: Hoge gele activatie hier betekent dat ik sterk leef vanuit geleerde regels, idealen en kenniskaders. Ik beoordeel situaties langs de lat van hoe het "zou moeten" zijn. Dit geeft stabiliteit en richting — maar kan ook rigiditeit en teleurstelling opleveren wanneer de werkelijkheid niet aan mijn architectuur voldoet.',
            en: 'High yellow profile: High yellow activation here means I live strongly from learned rules, ideals and knowledge frameworks. I judge situations against the yardstick of how things "ought" to be. That brings stability and direction — but it can also produce rigidity and disappointment when reality fails to meet my architecture.',
          },
          growth: {
            nl: 'Groeirichting: Duik in de driehoeken die ik het minst activeert — met name Impact Modus (Lover · Outlaw · Magician). Dat is precies het territorium die mijn systemen niet kunnen verklaren: emotionele chaos en blinde disruptie.',
            en: 'Growth direction: Dive into the triangles I activate least — Impact Mode in particular (Lover · Outlaw · Magician). That is exactly the territory my systems cannot explain: emotional chaos and blind disruption.',
          },
        },

        exploratie: {
          mode: { nl: 'Exploratie Modus', en: 'Exploration Mode' },
          networks: { nl: 'CEN · Openness · DMN', en: 'CEN · Openness · DMN' },
          tagline: {
            nl: 'Jij navigeert via perceptie, ontdekking en vorm.',
            en: 'You navigate through perception, discovery and form.',
          },
          what: {
            nl: 'Rechter, Ontdekker en Kunstenaar vormen de cognitieve driehoek van verfijning. Je hebt leren navigeren door scherp te analyseren (Judge), grenzen te verleggen (Explorer) en ervaring te vertalen naar expressie (Artist). Dit is het patroon van iemand die de wereld wil begrijpen door haar te doorzoeken — en wat ze vinden willen verwerken tot iets wat méér zegt dan de feiten.',
            en: 'Judge, Explorer and Artist form the cognitive triangle of refinement. You have learned to navigate by analysing sharply (Judge), pushing boundaries (Explorer) and translating experience into expression (Artist). This is the pattern of someone who wants to understand the world by searching through it — and to work whatever they find into something that says more than the facts do.',
          },
          drive: {
            nl: 'Je Culture picks activeren een netwerk dat evalueert, verkent en synthetiseert. Je hebt aangeleerd dat begrijpen meer waard is dan accepteren. Je cognitieve motor draait op nieuwsgierigheid en het verlangen om patronen te zien waar anderen ruis zien.',
            en: 'Your Culture picks activate a network that evaluates, explores and synthesises. You have learned that understanding is worth more than accepting. Your cognitive engine runs on curiosity and the desire to see patterns where others see noise.',
          },
          high: {
            nl: 'Hoge activatie in deze driehoek betekent dat je een sterke aangeleerde tendens hebt om te beoordelen vóór je handelt, breed te verkennen vóór je kiest, en ervaring te willen distilleren tot iets zinvols. Dit geeft diepgang en oorspronkelijkheid — maar kan leiden tot analyse-verlamming of overprikkeling wanneer de input de verwerkingscapaciteit overstijgt.',
            en: 'High activation in this triangle means you have a strong learned tendency to judge before you act, to explore widely before you choose, and to want to distil experience into something meaningful. That brings depth and originality — but it can lead to analysis paralysis or overstimulation when the input exceeds your processing capacity.',
          },
          growth: {
            nl: 'De tegenhanger hier is Engagement Modus (Caregiver · Trickster · Hero) — de driehoek van concrete actie, spelende subversie en directe inzet. Dat is het domein dat jouw verfijnde analyse soms overslaat: het gewoon dóen, het verbinden, het inzetten.',
            en: 'The counterpart here is Engagement Mode (Caregiver · Trickster · Hero) — the triangle of concrete action, playful subversion and direct commitment. That is the domain your refined analysis sometimes skips: simply doing it, connecting, stepping in.',
          },
        },

        impact: {
          mode: { nl: 'Impact Modus', en: 'Impact Mode' },
          networks: { nl: 'Limbisch · Salience · Agency', en: 'Limbic · Salience · Agency' },
          tagline: {
            nl: 'Jij navigeert via emotie, disruptie en transformatie.',
            en: 'You navigate through emotion, disruption and transformation.',
          },
          what: {
            nl: 'Minnaar, Outlaw en Magiër vormen de cognitieve driehoek van alchemie. Je hebt leren navigeren door je diep te verbinden (Lover), te doorbreken wat vast zit (Outlaw) en de werkelijkheid actief te her-schrijven (Magician). Dit is het patroon van iemand die verandering niet afwacht — maar haar veroorzaakt door aanwezig te zijn.',
            en: 'Lover, Outlaw and Magician form the cognitive triangle of alchemy. You have learned to navigate by connecting deeply (Lover), by breaking open what is stuck (Outlaw) and by actively re-writing reality (Magician). This is the pattern of someone who does not wait for change — but causes it simply by being present.',
          },
          drive: {
            nl: 'Je Culture picks activeren een netwerk dat voelt, confronteert en transformeert. Je aangeleerde navigatiestijl draait op intensiteit: verbinding als instrument, disruptie als methode, magie als overtuiging dat alles anders kan. Je hebt geleerd dat passiviteit de grootste kostenpost is.',
            en: 'Your Culture picks activate a network that feels, confronts and transforms. Your learned navigation style runs on intensity: connection as an instrument, disruption as a method, magic as the conviction that everything could be otherwise. You have learned that passivity is the biggest cost of all.',
          },
          high: {
            nl: 'Hoge activatie in Impact Modus betekent dat je sterk reageert vanuit emotionele intensiteit en het verlangen om impact te maken. Je bent aangeleerd om niet te accepteren wat is — maar het te bewegen. Dit geeft transformatieve kracht en magnetische aanwezigheid — maar kan leiden tot uitputting, overdrive of brandend gevoel als de transformatie uitblijft.',
            en: 'High activation in Impact Mode means you react strongly from emotional intensity and the desire to make an impact. You have been taught not to accept what is — but to move it. That brings transformative power and a magnetic presence — but it can lead to exhaustion, overdrive or a burning feeling when the transformation fails to arrive.',
          },
          growth: {
            nl: 'De tegenhanger hier is Idealisme Modus (Ruler · Innocent · Sage) — de driehoek van structuur, principe en kennis. Dat is wat jouw vuur soms mist: het kader dat de energie kanaliseert, het principe dat de richting houdt, de wijsheid die de actie vertraagt.',
            en: 'The counterpart here is Idealism Mode (Ruler · Innocent · Sage) — the triangle of structure, principle and knowledge. That is what your fire sometimes lacks: the frame that channels the energy, the principle that holds the direction, the wisdom that slows the action down.',
          },
        },

        engagement: {
          mode: { nl: 'Engagement Modus', en: 'Engagement Mode' },
          networks: { nl: 'Limbisch · Salience · Agency', en: 'Limbic · Salience · Agency' },
          tagline: {
            nl: 'Jij navigeert via verbinding, subversie en directe actie.',
            en: 'You navigate through connection, subversion and direct action.',
          },
          what: {
            nl: 'Verzorger, Trickster en Held vormen de cognitieve driehoek van actieve inzet. Je hebt leren navigeren door te beschermen en te voeden (Caregiver), door spelend te ontregelen (Trickster) en door direct in te grijpen wanneer het ertoe doet (Hero). Dit is het patroon van iemand die niet toekijkt — die zich inmengt, inzet en daadwerkelijk verschijnt.',
            en: 'Caregiver, Trickster and Hero form the cognitive triangle of active commitment. You have learned to navigate by protecting and nourishing (Caregiver), by playfully unsettling things (Trickster) and by intervening directly when it matters (Hero). This is the pattern of someone who does not stand by — who gets involved, commits, and actually shows up.',
          },
          drive: {
            nl: 'Je Culture picks activeren een netwerk dat de ander centraal stelt — zelfs wanneer dat via de achterdeur gaat (Trickster) of via frontale actie (Hero). Je hebt aangeleerd dat betrokkenheid de maatstaf is. Niet wat je weet of wilt — maar wat je doet.',
            en: 'Your Culture picks activate a network that puts the other person first — even when that happens through the back door (Trickster) or through frontal action (Hero). You have learned that involvement is the measure. Not what you know or want — but what you do.',
          },
          high: {
            nl: 'Hoge activatie in Engagement Modus betekent dat je sterk aanwezig bent in de levens van anderen, snel handelt wanneer iemand hulp nodig heeft, en moeite hebt om op afstand te blijven van wat fout gaat. Dit geeft loyaliteit en daadkracht — maar kan leiden tot overbelasting, het dragen van andermans last, of verlies van eigen richting.',
            en: 'High activation in Engagement Mode means you are strongly present in other people\'s lives, that you act fast when someone needs help, and that you struggle to keep your distance from what is going wrong. That brings loyalty and decisiveness — but it can lead to overload, to carrying other people\'s burdens, or to losing your own direction.',
          },
          growth: {
            nl: 'De tegenhanger hier is Exploratie Modus (Judge · Explorer · Artist) — de driehoek van perceptie, ontdekking en expressie. Dat is het domein dat jouw actiegeoriënteerde stijl soms overslaat: de tijd nemen om te beoordelen, te verkennen en iets voor jezelf te maken.',
            en: 'The counterpart here is Exploration Mode (Judge · Explorer · Artist) — the triangle of perception, discovery and expression. That is the domain your action-oriented style sometimes skips: taking the time to assess, to explore, and to make something for yourself.',
          },
        },
      },
    },

    // ── Standalone feedback form (validation + success copy) ──
    feedback: {
      emailRequired: { nl: 'Vul je e-mailadres in', en: 'Please enter your email address' },
      scoreRequired: { nl: 'Selecteer een score (1-9)', en: 'Please select a score (1-9)' },
      textRequired: {
        nl: 'Vul minimaal één tekstveld in',
        en: 'Please fill in at least one text field',
      },
      thanksTitle: { nl: 'Dank je wel voor je feedback!', en: 'Thank you for your feedback!' },
      thanksBody: {
        nl: 'Jouw reactie is ontvangen en draagt bij aan de verbetering van dit systeem.',
        en: 'Your response has been received and helps improve this system.',
      },
    },

    // ── Sample AI report sections ──
    sections: {
      identiteit: {
        title: { nl: 'De Identiteit', en: 'The Identity' },
        content: {
          nl: `**The Maverick**

De Maverick combineert de architecturale kracht van de Ruler met de disruptieve eerlijkheid van de Outlaw. Jij bouwt systemen die de wereld kunnen veranderen — en bent tegelijkertijd bereid die systemen te slopen wanneer ze niet meer dienen wat ze zouden moeten dienen.

*Dit is een modelinterpretatie van jouw antwoordprofiel, geen vastgestelde identiteit.*`,
          en: `**The Maverick**

The Maverick combines the architectural force of the Ruler with the disruptive honesty of the Outlaw. You build systems capable of changing the world — and you are willing, at the same time, to tear those systems down when they no longer serve what they were meant to serve.

*This is a model interpretation of your answer profile, not an established identity.*`,
        },
      },

      waarom: {
        title: { nl: 'Waarom Jij Dit Perspectief Gebruikt', en: 'Why You Use This Perspective' },
        content: {
          nl: `Jouw antwoordpatronen suggereren een zeldzame combinatie: de drang om orde te scheppen én de weigering om orde te accepteren die niet op waarheid is gebouwd. Binnen dit model wijst de hoge CEN-dominantie (76% Nature) op een biologisch verankerd vermogen om structuur te zien, te bouwen en te handhaven. Tegelijkertijd activeert de Salience-as (Outlaw/Trickster, 60% Nature) een scherp radar voor wat niet klopt — voor hypocrisie, voor systemen die zichzelf in stand houden ten koste van mensen.

De combinatie van Ruler en Outlaw is geen contradictie. Het is een navigatiestijl: jij bouwt vanuit principes, niet vanuit conventie. Binnen dit model suggereert jouw data dat je gezag erkent wanneer het verdiend is — en het aanvecht wanneer dat niet zo is.`,
          en: `Your answer patterns suggest a rare combination: the urge to create order and the refusal to accept any order that is not built on truth. Within this model, the high CEN dominance (76% Nature) points to a biologically anchored capacity to see, build and maintain structure. At the same time, the Salience axis (Outlaw/Trickster, 60% Nature) activates a sharp radar for what does not add up — for hypocrisy, for systems that sustain themselves at people's expense.

The combination of Ruler and Outlaw is not a contradiction. It is a navigation style: you build from principles, not from convention. Within this model, your data suggests that you recognise authority when it is earned — and challenge it when it is not.`,
        },
      },

      essentie: {
        title: { nl: 'De Essentie (Main Archetype)', en: 'The Essence (Main Archetype)' },
        content: {
          nl: `**Archetype & Groep:** Ruler | Ruling (CEN — Externe Structuur & Wet)

**TNM-Associatie:** Binnen dit model wordt de Ruler geassocieerd met het Central Executive Network — de verwerkingsmodus die gericht is op externe structuur, hiërarchie en langetermijnarchitectuur.

**Drijfveer:** Primair Nature-gedreven (76% Nature binnen de CEN-as). Vanuit dit scoreprofiel is het aannemelijk dat jouw drang om te leiden en te structureren biologisch verankerd is — geen aangeleerde strategie maar een instinctieve oriëntatie op verantwoordelijkheid.

**Meester Inzicht:** De Ruler functioneert als primaire gedragslens wanneer er iets op het spel staat. Jij ziet de architectuur van een situatie voordat anderen de details zien. Binnen dit model suggereert jouw data dat dit patroon het sterkst actief is onder druk — dat is het moment waarop de Ruler niet reageert maar regeert.`,
          en: `**Archetype & Group:** Ruler | Ruling (CEN — External Structure & Law)

**TNM Association:** Within this model the Ruler is associated with the Central Executive Network — the processing mode oriented toward external structure, hierarchy and long-term architecture.

**Driver:** Primarily Nature-driven (76% Nature within the CEN axis). On the basis of this score profile it is plausible that your urge to lead and to structure is biologically anchored — not a learned strategy but an instinctive orientation toward responsibility.

**Master Insight:** The Ruler functions as your primary behavioural lens whenever something is at stake. You see the architecture of a situation before others see the details. Within this model, your data suggests this pattern is most strongly active under pressure — that is the moment at which the Ruler does not react but rules.`,
        },
      },

      vermenigvuldiging: {
        title: {
          nl: 'De Vermenigvuldiging (Support Archetype)',
          en: 'The Multiplication (Support Archetype)',
        },
        content: {
          nl: `**Archetype & Groep:** Outlaw | Chaos (Salience — Disruptie & Waarheid)

**TNM-Associatie:** Binnen dit model wordt de Outlaw geassocieerd met het Salience Network — de verwerkingsmodus die gericht is op wat urgent, authentiek en onaanvaardbaar is.

**Rol:** De Outlaw vult de Ruler niet aan — hij daagt hem uit. Vanuit jouw scoreprofiel is het aannemelijk dat deze spanning productief is: de Ruler bouwt de structuur, de Outlaw test of die structuur de waarheid verdraagt.

**Hardware / Schaduw Check:** Main (Ruler, positie 12) en Support (Outlaw, positie 6) staan op de Paarse Lijn — 180° tegenpolen. Dit is geen hardware-resonantie maar schaduw-integratie. Binnen dit model is het aannemelijk dat jij bewust of onbewust werkt met de spanning tussen bouwen en vernietigen, tussen orde en chaos, tussen institutie en rebellie. Dit is het kernmechanisme van The Maverick.`,
          en: `**Archetype & Group:** Outlaw | Chaos (Salience — Disruption & Truth)

**TNM Association:** Within this model the Outlaw is associated with the Salience Network — the processing mode oriented toward what is urgent, authentic and unacceptable.

**Role:** The Outlaw does not complement the Ruler — it challenges him. On the basis of your score profile it is plausible that this tension is productive: the Ruler builds the structure, the Outlaw tests whether that structure can withstand the truth.

**Hardware / Shadow Check:** Main (Ruler, position 12) and Support (Outlaw, position 6) sit on the Purple Line — 180° opposites. This is not hardware resonance but shadow integration. Within this model it is plausible that you work, consciously or unconsciously, with the tension between building and destroying, between order and chaos, between institution and rebellion. This is the core mechanism of The Maverick.`,
        },
      },

      schaduw: {
        title: { nl: 'De Schaduw', en: 'The Shadow' },
        content: {
          nl: `Binnen dit model is het opmerkelijk dat jouw Shadow-archetype identiek is aan jouw Support-archetype. Dit suggereert dat jij al actief werkt met de energie van de Outlaw — maar de vraag is of dat bewust gebeurt of als reactie op externe druk.

**De Polarization Index:** Main (Ruler) en Shadow (Outlaw) staan op 180°. Vanuit de scoreverhoudingen is de gap significant — dit wijst op een gezonde maar nog niet volledig geïntegreerde spanning.

De Outlaw als schaduw betekent: de energie van radicale eerlijkheid, van het doorbreken van conventies omwille van waarheid, van het accepteren van verlies als prijs voor integriteit — dit is de brandstof die de Ruler nodig heeft om niet te degenereren tot een systeem dat zichzelf in stand houdt. Binnen dit model is het aannemelijk dat jouw groeipad ligt in het bewust kiezen voor Outlaw-energie, in plaats van er door omstandigheden in gedwongen te worden.`,
          en: `Within this model it is striking that your Shadow archetype is identical to your Support archetype. This suggests that you already work actively with the energy of the Outlaw — the question is whether that happens consciously or as a reaction to external pressure.

**The Polarization Index:** Main (Ruler) and Shadow (Outlaw) sit at 180°. Judging by the score ratios the gap is significant — which points to a healthy but not yet fully integrated tension.

The Outlaw as shadow means: the energy of radical honesty, of breaking through conventions for the sake of truth, of accepting loss as the price of integrity — this is the fuel the Ruler needs in order not to degenerate into a system that merely sustains itself. Within this model it is plausible that your growth path lies in consciously choosing Outlaw energy, rather than being forced into it by circumstance.`,
        },
      },

      blindspot: {
        title: { nl: 'De Blindspot', en: 'The Blindspot' },
        content: {
          nl: `Vanuit het scoreprofiel is het aannemelijk dat het gedragspatroon van de Trickster — speelsheid, ambiguïteit, het gebruik van humor en indirect taalgebruik als navigatiemiddel — bij anderen onbewust een reactie triggert die jij niet altijd ziet aankomen.

De Trickster opereert in de ruimte tussen regels. Jij, als Ruler-dominant profiel, leest die ruimte als ruis of als onbetrouwbaarheid. Het is aannemelijk dat jij mensen die via indirectheid opereren systematisch onderschat — en dat zij jou als rigide of voorspelbaar lezen, wat hen een strategisch voordeel geeft.

De Rode Lijn genereert geen punten en ontvangt geen bleed. Dit is structurele spanning: de Trickster is niet jouw vijand, maar jouw blinde vlek. Houd er rekening mee dat situaties die om diplomatieke ambiguïteit vragen — onderhandelingen, politieke omgevingen, creatieve chaos — de context zijn waar dit profiel het meeste adaptatie-energie kost.`,
          en: `On the basis of the score profile it is plausible that the Trickster's behavioural pattern — playfulness, ambiguity, the use of humour and indirect language as a means of navigation — unconsciously triggers a reaction in others that you do not always see coming.

The Trickster operates in the space between the rules. You, as a Ruler-dominant profile, read that space as noise or as unreliability. It is plausible that you systematically underestimate people who operate through indirectness — and that they read you as rigid or predictable, which gives them a strategic advantage.

The Red Line generates no points and receives no bleed. This is structural tension: the Trickster is not your enemy, but your blind spot. Bear in mind that situations calling for diplomatic ambiguity — negotiations, political environments, creative chaos — are the contexts in which this profile costs the most adaptation energy.`,
        },
      },

      visuele: {
        title: { nl: 'Visuele Analyse', en: 'Visual Analysis' },
        content: {
          nl: `De radar chart toont een profiel met twee dominante pieken: Ruler en Judge vormen samen een uitgesproken CEN-cluster aan de ordezijde van het wiel. De eerste laag (paars, Nature picks) is sterk geconcentreerd op deze as, met een secundaire piek op de Outlaw-Magician-Hero cluster.

De tweede schil (oranje, Culture picks) waaiert breder uit — met zichtbare activiteit op Trickster, Artist en Sage — wat suggereert dat de aangeleerde strategieën het profiel diversifiëren buiten de biologische kern.

Het dal tussen Trickster en Caregiver is opvallend: hier stroomt geen Green, Blue of Yellow bleed naartoe. Dit is de structurele blindezone van het profiel. De Innocent-score is aanwezig maar laag, wat binnen dit model wijst op beperkte resonantie met naïviteit of onbevangen vertrouwen. De Magician-piek in de Agency-groep is geometrisch interessant: als CultureForce-signaal suggereert het dat de aangeleerde strategie transformationele taal en systeemdenken inzet als primair communicatie-instrument.`,
          en: `The radar chart shows a profile with two dominant peaks: Ruler and Judge together form a pronounced CEN cluster on the order side of the wheel. The first layer (purple, Nature picks) is strongly concentrated on this axis, with a secondary peak on the Outlaw-Magician-Hero cluster.

The second shell (orange, Culture picks) fans out more widely — with visible activity on Trickster, Artist and Sage — which suggests that the learned strategies diversify the profile beyond its biological core.

The valley between Trickster and Caregiver is striking: no Green, Blue or Yellow bleed flows into it. This is the profile's structural blind zone. The Innocent score is present but low, which within this model points to limited resonance with naivety or unguarded trust. The Magician peak in the Agency group is geometrically interesting: as a CultureForce signal it suggests that the learned strategy deploys transformational language and systems thinking as its primary instrument of communication.`,
        },
      },

      alchemie: {
        title: { nl: 'De Alchemie van Individuatie', en: 'The Alchemy of Individuation' },
        content: {
          nl: `**De Switch:** Vanuit dit scoreprofiel is het aannemelijk dat de schakelbeweging tussen Ruler-modus en Outlaw-modus snel en grotendeels onbewust verloopt. De hoge Nature-percentages op beide assen (76% CEN, 60% Salience) suggereren dat beide modi biologisch beschikbaar zijn — geen van beide vereist significante adaptatie-energie. Het risico is niet dat de switch niet werkt, maar dat hij ongecontroleerd werkt: van structuurbouwer naar systeembreker zonder bewuste keuze.

**Nature vs. Culture Balans:** De Authenticity Index is sterk Nature-dominant. Met name op de Agency-as (Magician/Hero: 90% Nature) en de Limbic-as (Lover/Caregiver: 86% Nature) is de biologische stroom overweldigend. Binnen dit model suggereert dit dat ik grotendeels opereert vanuit instinctieve gedragspatronen — met weinig energieverlies door sociale aanpassing.

**De Paradox:** De spanning tussen Ruler (orde) en Outlaw (disruptie) is niet pathologisch — het is het centrale generatieve principe van dit profiel. De paradox vraagt niet om oplossing maar om bewoning.

**Hardware Resonantie:** De Judge-Ruler hardware-as is sterk actief. Beide groepsleden scoren hoog, wat binnen dit model wijst op een robuust structuurcircuit.

**CultureForce Netwerk:** De Gele Driehoek-activiteit concentreert zich rond Magician, Trickster en Artist — wat suggereert dat het aangeleerde cognitieve netwerk transformationeel en creatief gekleurd is, ondanks de dominante Nature-kern.`,
          en: `**The Switch:** On the basis of this score profile it is plausible that the shift between Ruler mode and Outlaw mode happens fast and largely unconsciously. The high Nature percentages on both axes (76% CEN, 60% Salience) suggest that both modes are biologically available — neither requires significant adaptation energy. The risk is not that the switch fails to work, but that it works uncontrolled: from structure-builder to system-breaker without a conscious choice.

**Nature vs. Culture Balance:** The Authenticity Index is strongly Nature-dominant. On the Agency axis in particular (Magician/Hero: 90% Nature) and the Limbic axis (Lover/Caregiver: 86% Nature), the biological current is overwhelming. Within this model this suggests that I largely operate from instinctive behavioural patterns — with little energy lost to social adaptation.

**The Paradox:** The tension between Ruler (order) and Outlaw (disruption) is not pathological — it is the central generative principle of this profile. The paradox does not ask to be solved, but to be inhabited.

**Hardware Resonance:** The Judge-Ruler hardware axis is strongly active. Both group members score high, which within this model points to a robust structural circuit.

**CultureForce Network:** Yellow Triangle activity concentrates around Magician, Trickster and Artist — which suggests that the learned cognitive network is transformational and creative in colour, despite the dominant Nature core.`,
        },
      },

      schakelbord: {
        title: { nl: 'Het Neurale Schakelbord', en: 'The Neural Switchboard' },
        content: {
          nl: `**De Focus-hendel:** Wanneer ik merk dat ik een situatie primair beoordeel op haar structurele tekortkomingen — pauzeer en stel mezelf de vraag: wat werkt hier al? Dit is geen positief denken, maar een bewust activeren van de Ruler-modus vóór de Outlaw het frame overneemt. Als experiment: begin één vergadering per week met een expliciete inventarisatie van wat al functioneert, voordat je je agenda voor verbetering presenteert.

**De Schaduw-injectie:** De Outlaw-energie is al aanwezig in dit profiel — de uitdaging is niet hem te activeren maar hem bewust te richten. Experiment: kies één systeem of afspraak in mijn omgeving die ik al lang als inefficiënt ervaar maar nooit hebt aangevochten. Schrijf in drie zinnen op waarom je het hebt laten bestaan. Dit opent de vraag of de Outlaw hier brandstof levert of comfort beschermt.

**De Blindspot-check:** Let deze week op momenten waarop ik iemand als 'onserious' of 'onbetrouwbaar' ervaar. Stel jezelf de reflectievraag: wat probeert deze persoon te communiceren via de indirecte route die ik niet zie? De Trickster-blindspot manifesteert zich vaak als ongeduld met mensen die spelen waar jij werkt.`,
          en: `**The Focus Lever:** When I notice that I am judging a situation primarily on its structural shortcomings — pause and ask myself: what is already working here? This is not positive thinking, but a conscious activation of Ruler mode before the Outlaw takes over the frame. As an experiment: start one meeting a week with an explicit inventory of what already functions, before you present your agenda for improvement.

**The Shadow Injection:** Outlaw energy is already present in this profile — the challenge is not to activate it but to aim it consciously. Experiment: pick one system or arrangement around me that I have long experienced as inefficient but have never challenged. Write down in three sentences why you have let it stand. That opens the question of whether the Outlaw is supplying fuel here or protecting comfort.

**The Blindspot Check:** This week, watch for the moments in which I experience someone as 'unserious' or 'unreliable'. Ask yourself the reflective question: what is this person trying to communicate by the indirect route that I am not seeing? The Trickster blindspot often shows up as impatience with people who play where you work.`,
        },
      },

      ontologie: {
        title: { nl: 'Ontologische Evolutie', en: 'Ontological Evolution' },
        content: {
          nl: `**Richting het Centrum:** Vanuit jouw scoreprofiel is het aannemelijk dat de meest vruchtbare beweging richting balans niet ligt in het temperen van de Ruler of de Outlaw — maar in het bewust verbinden van beide. De extreme uitslagen aan de CEN-kant (Judge + Ruler samen dominant) kunnen richting meer balans bewegen door de DMN-as (Sage, Artist) bewust te voeden: reflectie, abstractie, het loslaten van de uitkomst.

**Ontologische Vraag:** Wanneer je een systeem hebt gebouwd dat werkt — wie ben jij dan nog?

Deze vraag raakt de kern van de Maverick-paradox: identiteit die gebonden is aan het bouwen van orde heeft een existentieel probleem wanneer de orde er is. Het individuatiepad van dit profiel loopt via de ontdekking dat de waarde niet in het systeem zit — maar in de intentie waarmee het gebouwd werd.

**AI Agent Prompt:** Zie Sectie 11.`,
          en: `**Toward the Centre:** On the basis of your score profile it is plausible that the most fruitful movement toward balance lies not in tempering the Ruler or the Outlaw — but in consciously connecting the two. The extreme readings on the CEN side (Judge + Ruler dominant together) can move toward greater balance by deliberately feeding the DMN axis (Sage, Artist): reflection, abstraction, letting go of the outcome.

**Ontological Question:** Once you have built a system that works — who are you then?

This question touches the heart of the Maverick paradox: an identity bound to the building of order has an existential problem once the order exists. The individuation path of this profile runs through the discovery that the value does not lie in the system — but in the intention with which it was built.

**AI Agent Prompt:** See Section 11.`,
        },
      },

      neuroticisme: {
        title: { nl: 'Neuroticisme Trigger', en: 'Neuroticism Trigger' },
        content: {
          nl: `Binnen dit model is het aannemelijk dat mijn stresspatroon zich manifesteert als een diep gevoel van structurele incompetentie bij anderen — niet mijn eigen falen, maar het falen van systemen die ik verantwoordelijk acht. De Outlaw-Support versterkt dit: wanneer regels worden gebroken zonder reden of autoriteit haar legitimiteit verliest, viert de stressrespons op. Met een uitzonderlijk lage N-score (2) zal deze trigger zelden vuren — maar wanneer hij dat doet, is de respons koel, doelgericht en potentieel langdurig vastgehouden.`,
          en: `Within this model it is plausible that my stress pattern manifests as a deep sense of structural incompetence in others — not my own failure, but the failure of systems I hold responsible. The Outlaw Support amplifies this: when rules are broken without reason, or when authority loses its legitimacy, the stress response flares up. With an exceptionally low N score (2) this trigger will rarely fire — but when it does, the response is cool, purposeful and potentially held on to for a long time.`,
        },
      },

      superkracht: {
        title: { nl: 'Superkracht op de Werkvloer', en: 'Superpower in the Workplace' },
        content: {
          nl: `Vanuit dit scoreprofiel is het aannemelijk dat mijn professionele kernkwaliteit zich uit als het vermogen om *systemen te bouwen die zichzelf bevragen*. De Ruler-kern levert de architectuur; de Outlaw-Support levert de stresstest. Met een Authenticity Index die sterk Nature-dominant is (met name op de CEN- en Agency-as), opereert deze kwaliteit instinctief — ik hoef niet na te denken over of een structuur robuust is, ik voel het. Dit profiel gedijt bij organisaties in transitie, bij complexe herstructureringen of waar anderen vastlopen in legacy-systemen.`,
          en: `On the basis of this score profile it is plausible that my professional core quality expresses itself as the ability to *build systems that question themselves*. The Ruler core supplies the architecture; the Outlaw Support supplies the stress test. With an Authenticity Index that is strongly Nature-dominant (particularly on the CEN and Agency axes), this quality operates instinctively — I do not have to think about whether a structure is robust, I feel it. This profile thrives in organisations in transition, in complex restructurings, or wherever others get stuck in legacy systems.`,
        },
      },

      conflictstijl: {
        title: { nl: 'Conflictstijl', en: 'Conflict Style' },
        content: {
          nl: `Binnen dit model is het aannemelijk dat ik conflict benader als een *correctiemechanisme*, niet als emotionele ontlading. Lage A (39) gecombineerd met uitzonderlijk lage N (2) produceert een koelbloedige confrontatiestijl: rustig, doelgericht, zonder zichtbare emotie. De Ruler-Main confronteert via gezag en argumentstructuur; de Outlaw-Support voegt bereidheid toe om regels te breken als de situatie het vraagt. Escalatiepunt: wanneer de ander de structurele logica weigert te erkennen. Ná het conflict: het grootboek wordt bijgehouden, maar niet getoond.`,
          en: `Within this model it is plausible that I approach conflict as a *correction mechanism*, not as an emotional release. Low A (39) combined with exceptionally low N (2) produces a cold-blooded confrontation style: calm, purposeful, with no visible emotion. The Ruler Main confronts through authority and the structure of an argument; the Outlaw Support adds a willingness to break the rules when the situation calls for it. Escalation point: when the other party refuses to acknowledge the structural logic. After the conflict: the ledger is kept, but never shown.`,
        },
      },

      relatiepatroon: {
        title: { nl: 'Relatiepatroon', en: 'Relationship Pattern' },
        content: {
          nl: `Mijn antwoordprofiel suggereert een relatiedynamiek waarin ik *de architect ben die de ander ruimte geeft* — maar wel binnen een kader dat ik heb ontworpen. Hoge E (88) gecombineerd met lage A (39) en lage N (2) creëert een dominant, aantrekkelijk maar onvermurwbaar patroon. De Ruler-Main biedt stabiliteit en richting; de Outlaw-Support maakt me onvoorspelbaar genoeg om fascinerend te blijven. Valkuil: de partner ervaart de structuur als veiligheid totdat ze haar beperking voelt. Ik trek mogelijk mensen aan die vrijheid zoeken — en biedt hen orde.`,
          en: `My answer profile suggests a relationship dynamic in which I am *the architect who gives the other person room* — but within a frame that I have designed. High E (88) combined with low A (39) and low N (2) creates a dominant, attractive but unyielding pattern. The Ruler Main offers stability and direction; the Outlaw Support keeps me unpredictable enough to stay fascinating. Pitfall: the partner experiences the structure as safety until they feel its constraint. I may attract people who are looking for freedom — and offer them order.`,
        },
      },

      individuatiepad: {
        title: { nl: 'Individuatiepad', en: 'Individuation Path' },
        content: {
          nl: `Binnen dit model wijst mijn profiel op een individuatiepad waarin de paradox centraal staat: *de Ruler die de Outlaw niet vreest, maar hem ook niet volledig loslaat*. De spanning tussen Main en Support is hier geen externe frictie maar een intern architectuurprobleem — wanneer is het systeem of persoon goed genoeg om los te laten? Het schakelpunt is het moment dat ik iets vertrouw zonder het te controleren. De 180° schaduw-energie van de Outlaw is niet mijn tegenstander — het is de brandstof die mijn systemen levend houdt. Het individuatiepad loopt via *vertrouwen in onvolmaaktheid*.`,
          en: `Within this model my profile points to an individuation path in which the paradox is central: *the Ruler who does not fear the Outlaw, but does not fully let him go either*. The tension between Main and Support is not external friction here but an internal architectural problem — when is the system, or the person, good enough to let go of? The switching point is the moment I trust something without checking it. The Outlaw's 180° shadow energy is not my opponent — it is the fuel that keeps my systems alive. The individuation path runs through *trust in imperfection*.`,
        },
      },
    },
  },
};
