/** reportLegal translations — see translations/index.js
 *
 *  Namespace for the generated PDF / print report produced by
 *  AssessmentResults.generatePDFContent(): cover page + the legal page.
 *  Values may contain HTML entities and inline tags — they are injected
 *  straight into the generated document.
 */
export default {
  reportLegal: {
    // Locale used to format the report date.
    dateLocale: {
      nl: 'nl-NL',
      en: 'en-GB',
    },

    // ── Cover page ──
    cover: {
      brandSub: {
        nl: 'Advanced Consciousness Assessment',
        en: 'Advanced Consciousness Assessment',
      },
      support: {
        nl: (name) => `Support: ${name}`,
        en: (name) => `Support: ${name}`,
      },
    },

    // ── Legal page ──
    header: {
      title: {
        nl: 'Juridische Informatie',
        en: 'Legal Information',
      },
      subtitle: {
        nl: 'Lees deze pagina zorgvuldig door voordat u verder leest',
        en: 'Please read this page carefully before you read on',
      },
    },

    highlight: {
      nl: 'Dit rapport is gegenereerd door een AI-model en vormt <strong>geen klinische diagnose</strong>, medisch advies of psychologisch oordeel. De resultaten zijn indicatief binnen het Garden for Life-model en mogen niet worden gebruikt als vervanging voor professionele hulpverlening.',
      en: 'This report was generated by an AI model and does <strong>not constitute a clinical diagnosis</strong>, medical advice or psychological judgement. The results are indicative within the Garden for Life model and may not be used as a substitute for professional care.',
    },

    modelDisclaimer: {
      title: {
        nl: '1. Modeldisclaimer',
        en: '1. Model Disclaimer',
      },
      body: {
        nl: 'Garden for Life gebruikt het Deltawerken-Model, een metaforisch raamwerk gebaseerd op 12 archetypische patronen. Alle termen zoals &ldquo;Nature&rdquo;, &ldquo;Culture&rdquo;, &ldquo;Shadow&rdquo; en &ldquo;Polarization&rdquo; zijn <em>modelconcepten</em> &mdash; geen biologische, neurologische of medische feiten. De analyse beschrijft antwoordpatronen, niet uw persoonlijkheid als vaststaand gegeven.',
        en: 'Garden for Life uses the Deltawerken Model, a metaphorical framework based on 12 archetypal patterns. All terms such as &ldquo;Nature&rdquo;, &ldquo;Culture&rdquo;, &ldquo;Shadow&rdquo; and &ldquo;Polarization&rdquo; are <em>model concepts</em> &mdash; not biological, neurological or medical facts. The analysis describes answer patterns, not your personality as an established fact.',
      },
    },

    aiTransparency: {
      title: {
        nl: '2. AI-Transparantie (EU AI Act)',
        en: '2. AI Transparency (EU AI Act)',
      },
      intro: {
        nl: 'De persoonlijkheidsanalyse in dit rapport is gegenereerd door een groot taalmodel (LLM). Conform de EU AI Act informeren wij u dat:',
        en: 'The personality analysis in this report was generated by a large language model (LLM). In accordance with the EU AI Act we inform you that:',
      },
      items: {
        nl: [
          'De analyse is gebaseerd op uw antwoorden op de assessment-vragen en eventueel ge&uuml;ploade documenten',
          'Het AI-systeem kan onnauwkeurigheden, vooroordelen of hallucinaties bevatten',
          'De output mag niet worden beschouwd als objectieve waarheid of wetenschappelijk bewijs',
          'Er vindt g&eacute;&eacute;n geautomatiseerde besluitvorming plaats op basis van deze resultaten',
        ],
        en: [
          'The analysis is based on your answers to the assessment questions and on any uploaded documents',
          'The AI system may contain inaccuracies, biases or hallucinations',
          'The output may not be regarded as objective truth or scientific proof',
          'No automated decision-making takes place on the basis of these results',
        ],
      },
    },

    dataProtection: {
      title: {
        nl: '3. Gegevensbescherming (AVG / GDPR)',
        en: '3. Data Protection (GDPR)',
      },
      intro: {
        nl: 'Uw assessment-gegevens worden verwerkt op grond van uw uitdrukkelijke toestemming (Art. 6 lid 1a AVG). Bijzondere persoonsgegevens (antwoordpatronen die indirect psychologische kenmerken kunnen onthullen) worden verwerkt op grond van Art. 9 lid 2a AVG. U heeft te allen tijde het recht op:',
        en: 'Your assessment data is processed on the basis of your explicit consent (Art. 6(1)(a) GDPR). Special categories of personal data (answer patterns that may indirectly reveal psychological characteristics) are processed on the basis of Art. 9(2)(a) GDPR. At all times you have the right to:',
      },
      items: {
        nl: [
          'Inzage, rectificatie en verwijdering van uw gegevens',
          'Intrekking van uw toestemming',
          'Overdraagbaarheid van uw gegevens (dataportabiliteit)',
          'Het indienen van een klacht bij de Autoriteit Persoonsgegevens',
        ],
        en: [
          'Access to, rectification of and erasure of your data',
          'Withdrawal of your consent',
          'Portability of your data (data portability)',
          'Lodge a complaint with the Dutch Data Protection Authority (Autoriteit Persoonsgegevens)',
        ],
      },
    },

    retention: {
      title: {
        nl: '4. Gegevensbewaring',
        en: '4. Data Retention',
      },
      body: {
        nl: 'Het berekende profiel waaruit dit rapport is opgebouwd bestaat <strong>maximaal 24 uur</strong> op onze servers en wordt daarna automatisch en onherroepelijk verwijderd. Dit rapport is uw persoonlijke kopie — Garden for Life bewaart daarvan geen kopie. Maakt u een account aan, dan blijft daarin uitsluitend een gedeeltelijk profiel bewaard. Uw kristal-code verloopt niet en blijft altijd inwisselbaar.',
        en: 'The calculated profile this report is built from exists on our servers for <strong>a maximum of 24 hours</strong>, after which it is automatically and irrevocably deleted. This report is your personal copy — Garden for Life keeps no copy of it. If you create an account, all that is retained in it is a partial profile. Your crystal code does not expire and can be redeemed at any time.',
      },
    },

    intellectualProperty: {
      title: {
        nl: '5. Intellectueel Eigendom',
        en: '5. Intellectual Property',
      },
      body: {
        nl: 'Het Deltawerken-Model, de archetypische geometrie, de vragenlijst en de visuele ontwerpen zijn intellectueel eigendom van Garden for Life / Yuan Wu. Dit rapport is uitsluitend voor persoonlijk gebruik. Reproductie, distributie of commerci&euml;le exploitatie zonder schriftelijke toestemming is verboden.',
        en: 'The Deltawerken Model, the archetypal geometry, the questionnaire and the visual designs are the intellectual property of Garden for Life / Yuan Wu. This report is for personal use only. Reproduction, distribution or commercial exploitation without written permission is prohibited.',
      },
    },

    liability: {
      title: {
        nl: '6. Beperkingen &amp; Aansprakelijkheid',
        en: '6. Limitations &amp; Liability',
      },
      body: {
        nl: 'Garden for Life aanvaardt geen aansprakelijkheid voor beslissingen genomen op basis van dit rapport. Bij psychische klachten of zorgen wordt u dringend aangeraden contact op te nemen met een gekwalificeerde zorgprofessional. De resultaten zijn een startpunt voor zelfreflectie, niet een eindoordeel.',
        en: 'Garden for Life accepts no liability for decisions made on the basis of this report. If you have psychological complaints or concerns, you are strongly advised to contact a qualified healthcare professional. The results are a starting point for self-reflection, not a final verdict.',
      },
    },

    footerNote: {
      nl: 'Door dit rapport te downloaden bevestigt u kennis te hebben genomen van bovenstaande voorwaarden.<br/>Volledige juridische documenten: www.gardenforlife.nl &nbsp;&bull;&nbsp; Contact: info@gardenforlife.nl',
      en: 'By downloading this report you confirm that you have taken note of the conditions above.<br/>Full legal documents: www.gardenforlife.nl &nbsp;&bull;&nbsp; Contact: info@gardenforlife.nl',
    },
  },
};
